// Textos de la opción 2. Los productos salen de lib/content.ts.

export const copy2 = {
  es: {
    idea: "Tengo una idea",
    custom: "Software a la medida",
    customHint: "Tu idea, programada desde cero",
    section: {
      whatKicker: "Lo que hacemos",
      whatTitle: ["Dos formas de", "trabajar con Tapki"],
      paths: [
        {
          tag: "01 / A la medida",
          title: "Software a la medida",
          text: "Tienes una idea o un proceso que te quita tiempo. Lo diseñamos y programamos desde cero para tu negocio.",
          cta: "Cuéntanos tu idea",
        },
        {
          tag: "02 / Productos",
          title: "Productos listos",
          text: "Software probado que ya usan negocios reales. Lo activas rápido y pagas una mensualidad.",
          cta: "Ver productos",
        },
      ],
      productsKicker: "Productos",
      productsTitle: ["Listos para", "usar hoy"],
      problem: "El problema",
      live: "En uso",
      dev: "En desarrollo",
      demo: "Pedir demo",
      customKicker: "Software a la medida",
      customTitle: ["¿Tienes una idea?", "La convertimos en software."],
      customText: "Si tu problema no encaja en ningún producto, hacemos uno nuevo para ti. Así nacieron todos los productos de Tapki.",
      steps: [
        { title: "Nos cuentas", text: "Por WhatsApp nos explicas tu idea o el problema que quieres resolver." },
        { title: "La diseñamos", text: "Te proponemos la solución, el alcance y el precio, sin compromiso." },
        { title: "La construimos", text: "La programamos, la ponemos en marcha y te acompañamos después." },
      ],
      examplesLabel: "Lo que podemos hacer",
      examples: ["Apps web", "Paneles administrativos", "Sistemas con NFC y QR", "Automatizaciones", "Integraciones con WhatsApp", "Reportes y Excel"],
      ideaCta: "Cuéntanos tu idea",
      ideaMsg: "Hola Tapki, tengo una idea de software a la medida:",
      footer: "Software a la medida y productos listos · Popayán, Colombia",
      option1: "Ver opción 1",
    },
    menu: "Menú",
    close: "Cerrar",
    city: "Popayán, CO",
    chat: "Chatea",
    start: "Pedir demo",
    est: "EST. 2026 // POPAYÁN // COLOMBIA",
    count: (n: number) => `${n} PRODUCTOS · 1 TOQUE`,
    pill: (n: number) => `A la medida · ${n} productos`,
    lines: ["SOFTWARE", "A LA MEDIDA", "PRODUCTOS"],
    hint: "← mueve el mouse →",
    about:
      "Hacemos software a la medida para negocios y tenemos productos listos para usar: carta digital para restaurantes, control de asistencia, tarjetas NFC y un vendedor con IA para WhatsApp.",
    seeProducts: "Ver productos",
    contactTitle: "¿Tienes una idea de software?",
    contactSub: "Cuéntanosla por WhatsApp y la hacemos realidad a tu medida.",
    contactPlaceholder: "Describe tu idea",
    send: "Enviar",
    sound: "Sonido",
    studio: "Estudio de luz",
    color: "Color",
    size: "Tamaño",
    intensity: "Intensidad",
    screen: {
      lock: "9:41",
      hint: "Acerca tu iPhone a la placa",
      opened: "Tapki Menu",
      place: "La Fonda Payanesa",
      items: ["Bandeja paisa", "Tamal de pipián", "Salpicón payanés"],
    },
    quote: {
      title: "Cotiza tu proyecto",
      sub: "Elige lo que necesitas y te llega armado a WhatsApp.",
      product: "Producto",
      other: "Software a la medida",
      business: "Nombre de tu negocio",
      size: "Tamaño del negocio",
      sizes: ["Pequeño", "Mediano", "Grande"],
      when: "¿Para cuándo?",
      whens: ["Ya", "Este mes", "Solo estoy mirando"],
      notes: "Cuéntanos más (opcional)",
      submit: "Enviar por WhatsApp",
      msg: (p: string, b: string, s: string, w: string, n: string) =>
        `Hola Tapki, quiero cotizar ${p}.\nNegocio: ${b || "-"}\nTamaño: ${s}\nPara: ${w}${n ? `\nDetalles: ${n}` : ""}`,
    },
    bot: {
      title: "Asistente Tapki",
      status: "Respuestas al instante",
      hello: "¡Hola! Soy el asistente de Tapki. ¿Qué quieres saber?",
      placeholder: "Escribe tu pregunta",
      handoff: "Te respondemos por WhatsApp para darte la mejor respuesta.",
      openWa: "Abrir WhatsApp",
      faqs: [
        {
          q: "¿Qué es Tapki?",
          a: "Somos un equipo en Popayán que crea software completo para problemas concretos: Tapki Menu, Tapki Control, Tapki Card y Tapki Vendedor.",
        },
        {
          q: "¿Cómo funciona el NFC?",
          a: "Pones una placa Tapki en la mesa, la portería o tu tarjeta. La gente acerca su celular y se abre la página correcta, sin descargar nada. También trae QR por si el celular no tiene NFC.",
        },
        {
          q: "¿Cuánto cuesta?",
          a: "Depende del producto y del tamaño de tu negocio. Usa el cotizador o escríbenos y te enviamos el precio por WhatsApp.",
        },
        {
          q: "¿Puedo pedir algo a la medida?",
          a: "Sí. Si tu problema no encaja en ningún producto, lo convertimos en uno nuevo. Cuéntanos qué te quita tiempo.",
        },
      ],
    },
  },
  en: {
    idea: "I have an idea",
    custom: "Custom software",
    customHint: "Your idea, built from scratch",
    section: {
      whatKicker: "What we do",
      whatTitle: ["Two ways to", "work with Tapki"],
      paths: [
        {
          tag: "01 / Custom",
          title: "Custom software",
          text: "You have an idea or a process that eats your time. We design and build it from scratch for your business.",
          cta: "Tell us your idea",
        },
        {
          tag: "02 / Products",
          title: "Ready-made products",
          text: "Proven software already used by real businesses. Get started fast and pay monthly.",
          cta: "See products",
        },
      ],
      productsKicker: "Products",
      productsTitle: ["Ready to", "use today"],
      problem: "The problem",
      live: "Live",
      dev: "In development",
      demo: "Get a demo",
      customKicker: "Custom software",
      customTitle: ["Got an idea?", "We turn it into software."],
      customText: "If your problem doesn't fit any product, we build a new one for you. That's how every Tapki product started.",
      steps: [
        { title: "You tell us", text: "Explain your idea or the problem you want solved on WhatsApp." },
        { title: "We design it", text: "We propose the solution, scope and price, no strings attached." },
        { title: "We build it", text: "We code it, launch it and stay with you afterwards." },
      ],
      examplesLabel: "What we can build",
      examples: ["Web apps", "Admin dashboards", "NFC & QR systems", "Automations", "WhatsApp integrations", "Reports & Excel"],
      ideaCta: "Tell us your idea",
      ideaMsg: "Hi Tapki, I have a custom software idea:",
      footer: "Custom software and ready-made products · Popayán, Colombia",
      option1: "See option 1",
    },
    menu: "Menu",
    close: "Close",
    city: "Popayán, CO",
    chat: "Chat",
    start: "Get a demo",
    est: "EST. 2026 // POPAYÁN // COLOMBIA",
    count: (n: number) => `${n} PRODUCTS · 1 TAP`,
    pill: (n: number) => `Custom · ${n} products`,
    lines: ["CUSTOM", "SOFTWARE", "PRODUCTS"],
    hint: "← move your mouse →",
    about:
      "We build custom software for businesses and we have ready-to-use products: a digital menu for restaurants, staff attendance, NFC cards and an AI salesperson for WhatsApp.",
    seeProducts: "See products",
    contactTitle: "Got a software idea?",
    contactSub: "Tell us on WhatsApp and we'll build it your way.",
    contactPlaceholder: "Describe your idea",
    send: "Send",
    sound: "Sound",
    studio: "Light studio",
    color: "Color",
    size: "Size",
    intensity: "Intensity",
    screen: {
      lock: "9:41",
      hint: "Hold your iPhone near the tag",
      opened: "Tapki Menu",
      place: "La Fonda Payanesa",
      items: ["Bandeja paisa", "Tamal de pipián", "Salpicón payanés"],
    },
    quote: {
      title: "Quote your project",
      sub: "Pick what you need and it lands on WhatsApp, ready to go.",
      product: "Product",
      other: "Custom software",
      business: "Business name",
      size: "Business size",
      sizes: ["Small", "Medium", "Large"],
      when: "When?",
      whens: ["Now", "This month", "Just looking"],
      notes: "Tell us more (optional)",
      submit: "Send via WhatsApp",
      msg: (p: string, b: string, s: string, w: string, n: string) =>
        `Hi Tapki, I'd like a quote for ${p}.\nBusiness: ${b || "-"}\nSize: ${s}\nWhen: ${w}${n ? `\nDetails: ${n}` : ""}`,
    },
    bot: {
      title: "Tapki assistant",
      status: "Instant answers",
      hello: "Hi! I'm the Tapki assistant. What would you like to know?",
      placeholder: "Type your question",
      handoff: "We'll reply on WhatsApp so you get the best answer.",
      openWa: "Open WhatsApp",
      faqs: [
        {
          q: "What is Tapki?",
          a: "We're a team in Popayán, Colombia building complete software for specific problems: Tapki Menu, Tapki Control, Tapki Card and Tapki Vendedor.",
        },
        {
          q: "How does NFC work?",
          a: "You place a Tapki tag on the table, the front desk or your card. People tap their phone and the right page opens, no app needed. There's a QR backup for phones without NFC.",
        },
        {
          q: "How much does it cost?",
          a: "It depends on the product and the size of your business. Use the quote tool or message us and we'll send the price on WhatsApp.",
        },
        {
          q: "Can you build something custom?",
          a: "Yes. If your problem doesn't fit any product, we turn it into a new one. Tell us what's eating your time.",
        },
      ],
    },
  },
};
