// Textos de la opción 2. Los productos salen de lib/content.ts.

export const copy2 = {
  es: {
    menu: "Menú",
    close: "Cerrar",
    city: "Popayán, CO",
    chat: "Chatea",
    start: "Pedir demo",
    est: "EST. 2026 // POPAYÁN // COLOMBIA",
    count: (n: number) => `${n} PRODUCTOS · 1 TOQUE`,
    pill: (n: number) => `${n} productos`,
    lines: ["UN TOQUE", "ABRE", "SOLUCIONES"],
    unit: "(productos)",
    hint: "← mueve el mouse →",
    about:
      "Tapki crea programas distintos para problemas distintos: restaurantes, porterías, tarjetas de presentación y ventas por WhatsApp. Cada uno, lo más completo en su nicho.",
    seeProducts: "Ver productos",
    contactTitle: "Escríbenos por WhatsApp",
    contactSub: "Cuéntanos tu problema y te respondemos hoy.",
    contactPlaceholder: "Tu mensaje",
    send: "Enviar",
    sound: "Sonido",
    studio: "Estudio de luz",
    color: "Color",
    size: "Tamaño",
    intensity: "Intensidad",
    screen: {
      lock: "9:41",
      hint: "Acerca tu iPhone a la placa",
      opened: "Tapki Menu",
      place: "La Fonda Payanesa",
      items: ["Bandeja paisa", "Tamal de pipián", "Salpicón payanés"],
    },
    quote: {
      title: "Cotiza tu proyecto",
      sub: "Elige lo que necesitas y te llega armado a WhatsApp.",
      product: "Producto",
      other: "Algo nuevo",
      business: "Nombre de tu negocio",
      size: "Tamaño del negocio",
      sizes: ["Pequeño", "Mediano", "Grande"],
      when: "¿Para cuándo?",
      whens: ["Ya", "Este mes", "Solo estoy mirando"],
      notes: "Cuéntanos más (opcional)",
      submit: "Enviar por WhatsApp",
      msg: (p: string, b: string, s: string, w: string, n: string) =>
        `Hola Tapki, quiero cotizar ${p}.\nNegocio: ${b || "-"}\nTamaño: ${s}\nPara: ${w}${n ? `\nDetalles: ${n}` : ""}`,
    },
    bot: {
      title: "Asistente Tapki",
      status: "Respuestas al instante",
      hello: "¡Hola! Soy el asistente de Tapki. ¿Qué quieres saber?",
      placeholder: "Escribe tu pregunta",
      handoff: "Te respondemos por WhatsApp para darte la mejor respuesta.",
      openWa: "Abrir WhatsApp",
      faqs: [
        {
          q: "¿Qué es Tapki?",
          a: "Somos un equipo en Popayán que crea software completo para problemas concretos: Tapki Menu, Tapki Control, Tapki Card y Tapki Vendedor.",
        },
        {
          q: "¿Cómo funciona el NFC?",
          a: "Pones una placa Tapki en la mesa, la portería o tu tarjeta. La gente acerca su celular y se abre la página correcta, sin descargar nada. También trae QR por si el celular no tiene NFC.",
        },
        {
          q: "¿Cuánto cuesta?",
          a: "Depende del producto y del tamaño de tu negocio. Usa el cotizador o escríbenos y te enviamos el precio por WhatsApp.",
        },
        {
          q: "¿Puedo pedir algo a la medida?",
          a: "Sí. Si tu problema no encaja en ningún producto, lo convertimos en uno nuevo. Cuéntanos qué te quita tiempo.",
        },
      ],
    },
  },
  en: {
    menu: "Menu",
    close: "Close",
    city: "Popayán, CO",
    chat: "Chat",
    start: "Get a demo",
    est: "EST. 2026 // POPAYÁN // COLOMBIA",
    count: (n: number) => `${n} PRODUCTS · 1 TAP`,
    pill: (n: number) => `${n} products`,
    lines: ["ONE TAP", "OPENS", "SOLUTIONS"],
    unit: "(products)",
    hint: "← move your mouse →",
    about:
      "Tapki builds different programs for different problems: restaurants, front desks, business cards and WhatsApp sales. Each one, the most complete in its niche.",
    seeProducts: "See products",
    contactTitle: "Message us on WhatsApp",
    contactSub: "Tell us your problem and we'll reply today.",
    contactPlaceholder: "Your message",
    send: "Send",
    sound: "Sound",
    studio: "Light studio",
    color: "Color",
    size: "Size",
    intensity: "Intensity",
    screen: {
      lock: "9:41",
      hint: "Hold your iPhone near the tag",
      opened: "Tapki Menu",
      place: "La Fonda Payanesa",
      items: ["Bandeja paisa", "Tamal de pipián", "Salpicón payanés"],
    },
    quote: {
      title: "Quote your project",
      sub: "Pick what you need and it lands on WhatsApp, ready to go.",
      product: "Product",
      other: "Something new",
      business: "Business name",
      size: "Business size",
      sizes: ["Small", "Medium", "Large"],
      when: "When?",
      whens: ["Now", "This month", "Just looking"],
      notes: "Tell us more (optional)",
      submit: "Send via WhatsApp",
      msg: (p: string, b: string, s: string, w: string, n: string) =>
        `Hi Tapki, I'd like a quote for ${p}.\nBusiness: ${b || "-"}\nSize: ${s}\nWhen: ${w}${n ? `\nDetails: ${n}` : ""}`,
    },
    bot: {
      title: "Tapki assistant",
      status: "Instant answers",
      hello: "Hi! I'm the Tapki assistant. What would you like to know?",
      placeholder: "Type your question",
      handoff: "We'll reply on WhatsApp so you get the best answer.",
      openWa: "Open WhatsApp",
      faqs: [
        {
          q: "What is Tapki?",
          a: "We're a team in Popayán, Colombia building complete software for specific problems: Tapki Menu, Tapki Control, Tapki Card and Tapki Vendedor.",
        },
        {
          q: "How does NFC work?",
          a: "You place a Tapki tag on the table, the front desk or your card. People tap their phone and the right page opens, no app needed. There's a QR backup for phones without NFC.",
        },
        {
          q: "How much does it cost?",
          a: "It depends on the product and the size of your business. Use the quote tool or message us and we'll send the price on WhatsApp.",
        },
        {
          q: "Can you build something custom?",
          a: "Yes. If your problem doesn't fit any product, we turn it into a new one. Tell us what's eating your time.",
        },
      ],
    },
  },
};
